<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2014 - 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2014 - 2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<?php /** @var Creativestyle_AmazonPayments_Block_Login_Button $this */ ?>
<div class="account-login amazon-login">
    <div class="new-users">
        <div class="content">
            <h2><?php echo $this->helper('amazonpayments')->__('Use your Amazon Account') ?></h2>
            <?php // @codingStandardsIgnoreStart ?>
            <p>
                <?php echo $this->helper('amazonpayments')->__('With Amazon Pay, you can use the shipping and payment information stored in your Amazon account to place an order on this website. It\'s a convenient and trusted way to pay that\'s enjoyed by millions of people.'); ?>
                <?php echo $this->helper('amazonpayments')->__('By selecting Login with Amazon, you will be asked to sign-in securely to your Amazon account without leaving the shop.'); ?>
            </p>
            <?php // @codingStandardsIgnoreEnd ?>
        </div>
    </div>
    <div class="buttons-set">
        <div id="<?php echo $this->getContainerId(); ?>" class="<?php echo $this->getContainerClass(); ?>"></div>
    </div>
</div>
<?php if ($this->getMoveBefore() || $this->isCustomDesignSet()): ?>
    <script type="text/javascript">
        <?php if ($this->isCustomDesignSet()): ?>
            var buttonDiv = $('<?php echo $this->getContainerId(); ?>');
            <?php if ($buttonType = $this->getButtonType()): ?>
                buttonDiv.buttonType = '<?php echo $buttonType; ?>';
            <?php endif; ?>
            <?php if ($buttonSize = $this->getButtonSize()): ?>
                buttonDiv.buttonSize = '<?php echo $buttonSize; ?>';
            <?php endif; ?>
            <?php if ($buttonColor = $this->getButtonColor()): ?>
                buttonDiv.buttonColor = '<?php echo $buttonColor; ?>';
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($this->getMoveBefore()): ?>
            if ($('<?php echo $this->getMoveBefore(); ?>')) {
                $$('div.amazon-login').each(function(element) {
                    $('<?php echo $this->getMoveBefore(); ?>')
                        .insert({before: element.addClassName('position-before')});
                });
            }
        <?php endif; ?>
    </script>
<?php endif; ?>
