<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2015 - 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2015 - 2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<h1><?php echo $this->__('Redirecting, please wait...'); ?></h1>
<script type="text/javascript">//<![CDATA[
    var accessToken = (new RegExp('[?|&|#]<?php echo $this->getAccessTokenParamName(); ?>=([^&;]+?)(&|#|;|$)')
        .exec(location.hash) || [,""])[1].replace(/\+/g,'%20') || null;
    if (typeof accessToken === 'string' && accessToken.match(/^Atza/)) {
        Mage.Cookies.set('amazon_Login_accessToken', decodeURIComponent(accessToken), null, '/', null, true);
        setLocation('<?php echo $this->getRedirectUrl(); ?>'.replace(/%s/, accessToken));
    } else {
        setLocation('<?php echo $this->getFailureUrl(); ?>');
    }
//]]></script>
